name: CI-CD
on:
  push:
    branches: ["main"]    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker build chatservice
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./chatservice
          file: ./chatservice/Dockerfile
          push: true
          tags: 
            tsa182/imersao-chatservice:v1
            tsa182/imersao-chatservice:latest
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: 
              tsa182/imersao-gpt-webapp:v1
              tsa182/imersao-gpt-webapp:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Autenticar o AWS CLI
        run: echo "Configurar o AWS configure"
      - name: Configuração do Kubectl
        run: echo "configurar o kubectl"
      - name: Display dos aplicações
        run: echo "Executar o comando kubectl apply"
      

    
