name: CI-CD
on:
  push:
    branches: ["main"]    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autenticando no Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker build chatservice
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./chatservice
          file: ./chatservice/Dockerfile
          push: true
          tags: |
            tsa182/imersao-chatservice:v${{ github.run_number }}
            tsa182/imersao-chatservice:latest
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
              tsa182/imersao-gpt-webapp:v${{ github.run_number }}
              tsa182/imersao-gpt-webapp:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Autenticar o AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configuração do Kubectl
        run: echo "configurar o kubectl"
      - name: Display dos aplicações
        run: echo "Executar o comando kubectl apply"
      

    
